services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym_manager_app
    restart: unless-stopped
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "${APP_KEY}"
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: gym_manager_db
      DB_USERNAME: gym_manager_admin
      DB_PASSWORD: supersecurepassword
    depends_on:
      pgsql:
        condition: service_healthy
    networks:
      - gym_manager_network
    expose:
      - 8000
    volumes:
      - .:/var/www/html
  pgsql:
    image: postgres:17-alpine
    container_name: gym_manager_pgsql
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gym_manager_db
      POSTGRES_USER: gym_manager_admin
      POSTGRES_PASSWORD: supersecurepassword
    volumes:
      - gym_manager_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym_manager_admin -d gym_manager_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gym_manager_network

volumes:
  gym_manager_pgdata:

networks:
  gym_manager_network:
    driver: bridge
